version: '3.9'

services:
  hadoop-namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: hadoop-namenode
    environment:
      - CLUSTER_NAME=emis_cluster
    ports:
      - "9870:9870"
    volumes:
      - hadoop_namenode_data:/hadoop/dfs/name
    networks:
      - hadoop-spark

  hadoop-datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: hadoop-datanode
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://hadoop-namenode:8020
    volumes:
      - hadoop_datanode_data:/hadoop/dfs/data
    networks:
      - hadoop-spark
    depends_on:
      - hadoop-namenode

  spark-master:
    image: bde2020/spark-master:3.1.1-hadoop3.2
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      - hadoop-spark
    depends_on:
      - hadoop-namenode

  spark-worker:
    image: bde2020/spark-worker:3.1.1-hadoop3.2
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    networks:
      - hadoop-spark
    depends_on:
      - spark-master

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: spark
      MYSQL_PASSWORD: sparkpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - hadoop-spark

volumes:
  hadoop_namenode_data:
  hadoop_datanode_data:
  mysql_data:

networks:
  hadoop-spark:
    driver: bridge
